### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by CyberShadow**
A bunch of small fixes I noticed while editing an .il file generated by ildasm.

Please see the commit messages for details.

I might add to this during the next day or two.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Wow, thanks a lot!

So far it looks okay for merge. Would you like me to merge it right now or wait for a couple of days?

**Comment by CyberShadow** [comment]
Up to you, but in the former case I might send a follow-up PR :)

**Comment by ForNeVeR** [comment]
It's already night at my location, so I think I'll test and merge this PR tomorrow. And I'll be glad to accept any additional follow-up PRs.

**Comment by ForNeVeR** [comment]
I've checked the changes and they all are good. Thank you very much for your contribution. I'll publish new devel and stable versions soon.

**Pull request merged**
